version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "44020:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=production
      - MAIN_UPLOAD_PATH=data
      - SUB_VIDEO_PATH=videos
      - SUB_IMAGE_PATH=images
      - DATABASE_URL=mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mydatabasepassword
      - DATABASE_NAME=accident_prediction

  mysql:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/mysql/data
      - ./database/init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=mydatabasepassword

volumes:
  mysql-data:
